title: "Ultimate_Instrument"
description: "アルティメット・インストゥルメント（UI）および関係論的ノイズ論（RNT）の公開資料ポータル。"
theme: jekyll-theme-cayman
lang: ja
url: "https://rnt-ui.github.io"
# カスタムCSSを読み込む
include:
  - assets/css/custom.css
